name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version: `X.X.X`"
        required: true
        default: '1.0.0'
        type: string
      tag:
        description: "Tag"
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: 'tags/${{ inputs.tag }}'
          file: 'HelixNavigator-${{ inputs.version }}.*'
          target: 'pkgs/'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: ncipollo/release-action@v1
        with:
          name: v${{ inputs.version }}
          artifacts: "pkgs/HelixNavigator-${{ inputs.version }}.*"
          draft: true
          prerelease: true
